version: '3.8'
services:
  localstack:
    image: localstack/localstack
    container_name: "localstack_services"
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,lambda,ecr,ecs,codebuild,codedeploy,apigateway,glue,redshift
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./localstack-data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
